//导入模块路径
require.config({
    baseUrl:".",
    paths:{
        "swiper":"libs/swiper.min",
        "jquery":"libs/jquery",
        "tools":"utils/tools",
        "cookie":"libs/jquery.cookie",
        "public":"utils/public",
        "ajax":"utils/ajax"
    }
})